# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: A.K.M. Ashrafuzzaman
description: "My blog"
keywords: "blog, web, jitu, personal site"
url: http://ashrafuzzaman.github.io
baseurl: ""

# google_analytics: UA-52446115-1
repo: https://github.com/ashrafuzzaman
disqus_shortname: "ashraf_zmn"
disqus_site_shortname: "ashrafuzzaman"

# Author settings
author:
  name      : A.K.M. Ashrafuzzaman
  job       : Engineering Manager @Newscred
  bio       : "A am muslim and a software engineer. Love building cool software and to contribute in open source projects. Love challenges and love to play table tennis."
  thumb     : images/author.jpg
  email     : ashrafuzzaman.g2@gmail.com
  url       : http://ashrafuzzaman.github.io
  github    : https://github.com/ashrafuzzaman
  twitter   : http://twitter.com/ashrafuzzaman
  linkedin  : https://www.linkedin.com/in/a-k-m-ashrafuzzaman-8b97168

# navbar pages
navbar:
  # - slug: about
  #   title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]